-- ============================================================
-- AI Events Ingestion — database schema
-- ============================================================
-- This file no longer DEFINES the schema, and piping it into MySQL does
-- nothing (it is comments only). The previous version DROPped every table on
-- run and had drifted out of sync with the code — that is exactly what the
-- migration system below replaces.
--
-- The schema is now managed by ordered migrations in /migrations, applied by a
-- runner that records what it has run, so a fresh install and an existing
-- production database converge to the same state with no destructive steps.
--
--   Fresh install / apply pending changes:   npm run db:migrate
--   Show applied vs pending:                  npm run db:migrate:status
--   Capture the live DB's real DDL:           npm run db:dump-schema
--   Seed the initial admin users:             npm run db:seed
--
-- Canonical schema lives in:
--   migrations/0001_baseline.sql            -- all 11 tables, current shape
--   migrations/0002_reconcile.sql           -- converge drifted ENUM columns
--   migrations/0003_performance_indexes.sql -- composite indexes for hot paths
--
-- To inspect the schema, read 0001_baseline.sql (or run db:dump-schema against
-- a live database to see its actual DDL).
-- ============================================================
