'use client';

import Link from 'next/link';
import { useState, type FormEvent } from 'react';
import { ArrowRight, CalendarDays, CheckCircle2, Mail, ShieldCheck, Sparkles } from 'lucide-react';
import { api, PRODUCT_NAME } from '@/lib/ai-calendar';
import { LoadingButton } from '@/components/ai-calendar/ui';

export default function LoginPage() {
  const [email, setEmail] = useState(''); const [busy, setBusy] = useState(false); const [sent, setSent] = useState(false); const [error, setError] = useState(''); const [devLink, setDevLink] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); try { const result = await api<{ ok?: boolean; devLink?: string }>('/api/auth/request', { method: 'POST', body: JSON.stringify({ email: email.trim().toLowerCase() }) }); setSent(true); setDevLink(result.devLink || ''); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not send the sign-in link'); } finally { setBusy(false); } }
  return <main className="cal-login"><div className="cal-login__ambient cal-login__ambient--one"/><div className="cal-login__ambient cal-login__ambient--two"/><section className="cal-login__story"><div className="cal-login__brand"><span className="cal-brand-mark"><CalendarDays size={22}/></span><strong>{PRODUCT_NAME}</strong></div><div className="cal-login__story-copy"><p className="cal-eyebrow">Intelligent event operations</p><h1>One reliable calendar from every community source.</h1><p>Discover, normalize, review, and publish local events with an auditable AI workflow built for multi-tenant teams.</p><div className="cal-login__proof"><span><Sparkles size={17}/>Agent-powered source discovery</span><span><ShieldCheck size={17}/>Human review and duplicate control</span><span><CheckCircle2 size={17}/>Live, traceable publishing runs</span></div></div><p className="cal-login__caption">Purpose-built for public calendars, schools, arts organizations, and civic networks.</p></section><section className="cal-login__panel"><div className="cal-login__card">{sent ? <div className="cal-login__sent"><span className="cal-login__mail"><Mail size={24}/></span><p className="cal-eyebrow">Link sent</p><h2>Check your inbox</h2><p>We sent a secure sign-in link to <strong>{email}</strong>. The link expires shortly.</p>{devLink && <Link className="cal-button cal-button--primary" href={devLink}>Open development sign-in link<ArrowRight size={16}/></Link>}<button className="cal-link-button" onClick={() => { setSent(false); setDevLink(''); }}>Use a different email</button></div> : <><div className="cal-login__mobile-brand"><span className="cal-brand-mark"><CalendarDays size={20}/></span><strong>{PRODUCT_NAME}</strong></div><p className="cal-eyebrow">Welcome back</p><h2>Sign in to your workspace</h2><p className="cal-login__help">Enter your approved work email. No password required.</p><form onSubmit={submit} className="cal-form-stack"><label className="cal-field"><span>Work email</span><div className="cal-input-wrap"><Mail size={17}/><input className="cal-input" type="email" value={email} onChange={event => setEmail(event.target.value)} autoComplete="email" placeholder="you@organization.org" required autoFocus/></div></label>{error && <div className="cal-inline-error" role="alert">{error}</div>}<LoadingButton busy={busy}>Send secure sign-in link<ArrowRight size={16}/></LoadingButton></form><div className="cal-login__security"><ShieldCheck size={16}/><span>Access is limited to invited users and protected by a secure, same-origin session.</span></div></>}</div><p className="cal-login__legal">By continuing, you agree to your organization’s data and access policies.</p></section></main>;
}
