'use client';

import { useEffect, useState, type FormEvent } from 'react';
import { Building2, Globe2, Plus, Save, ShieldCheck, Trash2, UserPlus, Users } from 'lucide-react';
import { api, rows, type Community, type Destination, type UserRow } from '@/lib/ai-calendar';
import { useCalendar } from './shell';
import { useApi } from './use-api';
import { Badge, Button, Card, EmptyState, ErrorState, Field, LoadingButton, Modal, PageHeader, Skeleton, StatusBadge } from './ui';

export function CommunitiesPage() {
  const { me } = useCalendar();
  const query = useApi<Community[] | { items: Community[] }>(me.role === 'platform_admin' ? '/api/communities' : null);
  const [creating, setCreating] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  if (me.role !== 'platform_admin') return <ErrorState message="Only platform administrators can manage communities."/>;
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget); try { await api('/api/communities', { method: 'POST', body: JSON.stringify({ name: form.get('name'), slug: form.get('slug'), timezone: form.get('timezone'), defaultMode: form.get('defaultMode') }) }); setCreating(false); await query.reload(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not create community'); } finally { setBusy(false); } }
  async function toggle(community: Community) { await api(`/api/communities/${community.id}`, { method: 'PATCH', body: JSON.stringify({ status: community.status === 'active' ? 'suspended' : 'active' }) }); await query.reload(); }
  const communities = rows(query.data);
  return <><PageHeader eyebrow="Platform administration" title="Communities" description="Control tenant workspaces, publishing defaults, and operating status." actions={<Button onClick={() => setCreating(true)}><Plus size={16}/>New community</Button>}/><Card>{query.loading ? <Skeleton rows={7}/> : query.error ? <ErrorState message={query.error} retry={query.reload}/> : !communities.length ? <EmptyState icon={<Building2/>} title="No communities" body="Create the first tenant workspace to begin."/> : <div className="cal-responsive-table"><table><thead><tr><th>Community</th><th>Timezone</th><th>Default mode</th><th>Destination</th><th>Status</th><th/></tr></thead><tbody>{communities.map(community => <tr key={community.id}><td><strong>{community.name}</strong><span>/{community.slug}</span></td><td>{community.timezone}</td><td><StatusBadge status={community.defaultMode}/></td><td>{community.defaultDestinationId ? `#${community.defaultDestinationId}` : 'Not configured'}</td><td><StatusBadge status={community.status}/></td><td><Button variant="ghost" onClick={() => toggle(community)}>{community.status === 'active' ? 'Suspend' : 'Activate'}</Button></td></tr>)}</tbody></table></div>}</Card>{creating && <Modal title="Create community" close={() => setCreating(false)}><form className="cal-form-stack" onSubmit={create}>{error && <ErrorState message={error}/>}<Field label="Community name"><input className="cal-input" name="name" required placeholder="Oberlin Community"/></Field><Field label="URL slug"><input className="cal-input" name="slug" required pattern="[a-z0-9-]+" placeholder="oberlin"/></Field><Field label="Timezone"><input className="cal-input" name="timezone" required defaultValue="America/New_York"/></Field><Field label="Default publishing mode"><select className="cal-select" name="defaultMode"><option value="restricted">Restricted — review required</option><option value="unrestricted">Unrestricted — automatic publishing</option></select></Field><div className="cal-form-actions"><Button type="button" variant="secondary" onClick={() => setCreating(false)}>Cancel</Button><LoadingButton busy={busy}>Create community</LoadingButton></div></form></Modal>}</>;
}

export function UsersPage() {
  const { me, communities } = useCalendar(); const query = useApi<UserRow[] | { items: UserRow[] }>(me.role === 'reviewer' ? null : '/api/users');
  const [inviting, setInviting] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  if (me.role === 'reviewer') return <ErrorState message="You do not have permission to manage users."/>;
  async function invite(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget); try { await api('/api/users', { method: 'POST', body: JSON.stringify({ email: form.get('email'), name: form.get('name') || undefined, role: form.get('role'), communityId: form.get('communityId') ? Number(form.get('communityId')) : me.communityId, canReviewAllSources: form.get('canReviewAllSources') === 'on' }) }); setInviting(false); await query.reload(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not add user'); } finally { setBusy(false); } }
  async function toggle(user: UserRow) { await api(`/api/users/${user.id}`, { method: 'PATCH', body: JSON.stringify({ status: user.status === 'active' ? 'disabled' : 'active' }) }); await query.reload(); }
  const users = rows(query.data);
  return <><PageHeader eyebrow="Access control" title="Users" description="Assign roles and review scope for the people operating this calendar." actions={<Button onClick={() => setInviting(true)}><UserPlus size={16}/>Add user</Button>}/><Card>{query.loading ? <Skeleton rows={7}/> : query.error ? <ErrorState message={query.error} retry={query.reload}/> : !users.length ? <EmptyState icon={<Users/>} title="No users" body="Add an administrator or reviewer to this workspace."/> : <div className="cal-responsive-table"><table><thead><tr><th>User</th><th>Role</th>{me.role === 'platform_admin' && <th>Community</th>}<th>Review scope</th><th>Status</th><th/></tr></thead><tbody>{users.map(user => <tr key={user.id}><td><strong>{user.name || user.email.split('@')[0]}</strong><span>{user.email}</span></td><td><Badge>{user.role.replaceAll('_', ' ')}</Badge></td>{me.role === 'platform_admin' && <td>{communities.find(c => c.id === user.communityId)?.name || (user.communityId ? `Community ${user.communityId}` : 'Platform')}</td>}<td>{user.canReviewAllSources ? 'All sources' : 'Assigned sources'}</td><td><StatusBadge status={user.status}/></td><td><Button variant="ghost" onClick={() => toggle(user)}>{user.status === 'active' ? 'Disable' : 'Enable'}</Button></td></tr>)}</tbody></table></div>}</Card>{inviting && <Modal title="Add user" close={() => setInviting(false)}><form className="cal-form-stack" onSubmit={invite}>{error && <ErrorState message={error}/>}<Field label="Name"><input className="cal-input" name="name" placeholder="Alex Morgan"/></Field><Field label="Work email"><input className="cal-input" type="email" name="email" required placeholder="alex@example.org"/></Field><Field label="Role"><select className="cal-select" name="role" defaultValue="reviewer">{me.role === 'platform_admin' && <option value="platform_admin">Platform admin</option>}<option value="community_admin">Community admin</option><option value="reviewer">Reviewer</option></select></Field>{me.role === 'platform_admin' && <Field label="Community"><select className="cal-select" name="communityId"><option value="">Platform access</option>{communities.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>}<label className="cal-checkbox"><input type="checkbox" name="canReviewAllSources"/><span><strong>Review all sources</strong><small>Otherwise, this reviewer only sees assigned sources.</small></span></label><div className="cal-form-actions"><Button type="button" variant="secondary" onClick={() => setInviting(false)}>Cancel</Button><LoadingButton busy={busy}>Add user</LoadingButton></div></form></Modal>}</>;
}

export function SettingsPage() {
  const { me, communityId } = useCalendar(); const effective = communityId ?? me.communityId;
  const communityQuery = useApi<Community>(effective ? `/api/communities/${effective}` : null); const destinationsQuery = useApi<Destination[] | { items: Destination[] }>(effective ? `/api/destinations?communityId=${effective}` : null);
  const [community, setCommunity] = useState<Community | null>(null); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  useEffect(() => { if (communityQuery.data) setCommunity(communityQuery.data); }, [communityQuery.data]);
  async function saveCommunity(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!community) return; setBusy('community'); setError(''); try { await api(`/api/communities/${community.id}`, { method: 'PATCH', body: JSON.stringify({ name: community.name, timezone: community.timezone, defaultMode: community.defaultMode, defaultDestinationId: community.defaultDestinationId }) }); await communityQuery.reload(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not save settings'); } finally { setBusy(''); } }
  if (!effective) return <><PageHeader eyebrow="Configuration" title="Settings" description="Choose a community from the workspace switcher to manage its configuration."/><EmptyState icon={<Globe2/>} title="Select a community" body="Platform-wide settings are managed per tenant to keep destinations and defaults isolated."/></>;
  return <><PageHeader eyebrow="Configuration" title="Settings" description="Set tenant defaults and manage where approved events are published."/>{error && <ErrorState message={error}/>}<div className="cal-settings-grid"><Card><div className="cal-card-header"><div><h2>Community defaults</h2><p>Core identity and publishing behavior.</p></div><Building2 size={19}/></div>{communityQuery.loading || !community ? <Skeleton rows={5}/> : <form className="cal-form-stack" onSubmit={saveCommunity}><Field label="Community name"><input className="cal-input" value={community.name} onChange={e => setCommunity({ ...community, name: e.target.value })}/></Field><Field label="Timezone"><input className="cal-input" value={community.timezone} onChange={e => setCommunity({ ...community, timezone: e.target.value })}/></Field><Field label="Default publishing mode"><select className="cal-select" value={community.defaultMode} onChange={e => setCommunity({ ...community, defaultMode: e.target.value as Community['defaultMode'] })}><option value="restricted">Restricted — review required</option><option value="unrestricted">Unrestricted — automatic publishing</option></select></Field><Field label="Default destination"><select className="cal-select" value={community.defaultDestinationId ?? ''} onChange={e => setCommunity({ ...community, defaultDestinationId: e.target.value ? Number(e.target.value) : null })}><option value="">No default destination</option>{rows(destinationsQuery.data).filter(d => d.active).map(d => <option value={d.id} key={d.id}>{d.name}</option>)}</select></Field><div className="cal-form-actions"><LoadingButton busy={busy === 'community'}><Save size={15}/>Save changes</LoadingButton></div></form>}</Card><Card><div className="cal-card-header"><div><h2>Publishing destinations</h2><p>Connected calendars and downstream systems.</p></div><ShieldCheck size={19}/></div>{destinationsQuery.loading ? <Skeleton rows={5}/> : destinationsQuery.error ? <ErrorState message={destinationsQuery.error} retry={destinationsQuery.reload}/> : rows(destinationsQuery.data).length ? <div className="cal-destination-list">{rows(destinationsQuery.data).map(destination => <div key={destination.id}><span className="cal-list-icon"><Globe2 size={17}/></span><div><strong>{destination.name}</strong><span>{destination.type.replaceAll('_', ' ')}</span></div><StatusBadge status={destination.active ? 'active' : 'disabled'}/><Button variant="ghost" aria-label={`Delete ${destination.name}`}><Trash2 size={15}/></Button></div>)}</div> : <EmptyState icon={<Globe2/>} title="No destinations" body="Connect a calendar, CommunityHub, webhook, or iCal feed through the API."/>}</Card></div></>;
}
