'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useMemo, useState, type FormEvent } from 'react';
import { Activity, ArrowRight, CalendarCheck, Clock3, Globe2, Inbox, Mail, Play, Plus, Radar, RefreshCw, Send, Settings2 } from 'lucide-react';
import { api, formatDate, rows, type Community, type Run, type Source } from '@/lib/ai-calendar';
import { useCalendar } from './shell';
import { useApi } from './use-api';
import { Badge, Button, Card, EmptyState, ErrorState, Field, Kpi, LoadingButton, PageHeader, Skeleton, StatusBadge } from './ui';

type Dashboard = { activeSources: number; pending: number; approved: number; submitted: number; duplicate: number; recentRuns: Run[] };

export function DashboardPage() {
  const { me } = useCalendar();
  const dashboard = useApi<Dashboard>('/api/dashboard');
  const communityQuery = useApi<Community[] | { items: Community[] }>(me.role === 'platform_admin' ? '/api/communities' : null);
  return <><PageHeader eyebrow="Operations" title="Calendar command center" description="Monitor ingestion, review decisions, and publishing health across your event pipeline." actions={<Link href="/sources/new"><Button><Plus size={16}/>Add source</Button></Link>}/>{dashboard.loading ? <Skeleton rows={5}/> : dashboard.error ? <ErrorState message={dashboard.error} retry={dashboard.reload}/> : dashboard.data && <><div className="cal-kpi-grid"><Kpi label="Active sources" value={dashboard.data.activeSources} foot="Collecting events" href="/sources" icon={<Radar size={18}/>}/><Kpi label="Pending review" value={dashboard.data.pending} foot="Needs a decision" href="/review" icon={<Inbox size={18}/>}/><Kpi label="Approved" value={dashboard.data.approved} foot="Cleared by reviewers" href="/review?status=approved" icon={<CalendarCheck size={18}/>}/><Kpi label="Published" value={dashboard.data.submitted} foot="Sent to destinations" href="/review?status=submitted" icon={<Send size={18}/>}/></div><div className="cal-dashboard-grid"><Card><div className="cal-card-header"><div><p className="cal-eyebrow">Activity</p><h2>Recent agent runs</h2></div><Link href="/sources" className="cal-text-link">View sources<ArrowRight size={14}/></Link></div>{dashboard.data.recentRuns.length ? <div className="cal-list">{dashboard.data.recentRuns.map(run => <Link href={`/runs/${run.id}`} className="cal-run-row" key={run.id}><div className="cal-list-icon"><Activity size={17}/></div><div><strong>{run.runKind === 'discovery' ? 'Source discovery' : 'Event extraction'}</strong><span>Run #{run.id} · {run.phase || 'Initializing'}</span></div><StatusBadge status={run.status}/><span className="cal-row-time">{formatDate(run.startedAt)}</span><ArrowRight size={15}/></Link>)}</div> : <EmptyState title="No runs yet" body="Start a source run to watch its agent timeline here." icon={<Activity size={20}/>}/>}</Card>{me.role === 'platform_admin' && <Card><div className="cal-card-header"><div><p className="cal-eyebrow">Tenants</p><h2>Communities</h2></div><Link href="/communities" className="cal-text-link">Manage<ArrowRight size={14}/></Link></div>{communityQuery.loading ? <Skeleton rows={4}/> : <div className="cal-community-stack">{rows(communityQuery.data).slice(0, 5).map(community => <Link href={`/communities?selected=${community.id}`} key={community.id}><span className="cal-community-initial">{community.name[0]}</span><div><strong>{community.name}</strong><span>{community.timezone}</span></div><StatusBadge status={community.status}/></Link>)}</div>}</Card>}</div></>}</>;
}

export function SourcesPage() {
  const { me, communities } = useCalendar();
  const query = useApi<Source[] | { items: Source[] }>('/api/sources');
  const [search, setSearch] = useState('');
  const sourceRows = useMemo(() => rows(query.data).filter(source => `${source.name} ${source.orgName || ''}`.toLowerCase().includes(search.toLowerCase())), [query.data, search]);
  return <><PageHeader eyebrow="Ingestion" title="Sources" description="Manage every website and inbox that feeds events into your calendars." actions={<Link href="/sources/new"><Button><Plus size={16}/>Add source</Button></Link>}/><Card><div className="cal-table-tools"><input className="cal-input" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search sources" aria-label="Search sources"/><Badge>{sourceRows.length} sources</Badge></div>{query.loading ? <Skeleton rows={7}/> : query.error ? <ErrorState message={query.error} retry={query.reload}/> : !sourceRows.length ? <EmptyState icon={<Radar size={20}/>} title="No sources found" body="Add a website or inbox to begin discovering events." action={<Link href="/sources/new"><Button>Add source</Button></Link>}/> : <div className="cal-responsive-table"><table><thead><tr><th>Source</th>{me.role === 'platform_admin' && <th>Community</th>}<th>Type</th><th>Mode</th><th>Discovery</th><th>State</th><th/></tr></thead><tbody>{sourceRows.map(source => <tr key={source.id}><td><Link href={`/sources/${source.id}`} className="cal-table-title">{source.name}</Link><span>{source.url || source.orgWebsite || 'Email ingestion'}</span></td>{me.role === 'platform_admin' && <td>{communities.find(c => c.id === source.communityId)?.name || `Community ${source.communityId}`}</td>}<td><span className="cal-inline-icon">{source.sourceType === 'web' ? <Globe2 size={15}/> : <Mail size={15}/>} {source.sourceType}</span></td><td><StatusBadge status={source.mode || 'default'}/></td><td><StatusBadge status={source.discoveryStatus}/></td><td><StatusBadge status={source.active ? 'active' : 'disabled'}/></td><td><Link href={`/sources/${source.id}`} aria-label={`Open ${source.name}`}><ArrowRight size={16}/></Link></td></tr>)}</tbody></table></div>}</Card></>;
}

export function NewSourcePage() {
  const router = useRouter(); const { me, communities, communityId } = useCalendar();
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [type, setType] = useState<'web' | 'email'>('web');
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget);
    try { const result = await api<{ id: number }>('/api/sources', { method: 'POST', body: JSON.stringify({ name: form.get('name'), sourceType: type, ...(type === 'web' ? { url: form.get('url') } : {}), specialInstructions: form.get('specialInstructions') || undefined, ...(me.role === 'platform_admin' ? { communityId: Number(form.get('communityId') || communityId) } : {}) }) }); router.push(`/sources/${result.id}`); }
    catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not add source'); setBusy(false); }
  }
  return <><PageHeader eyebrow="New ingestion source" title="Add a source" description="AI Calendar will inspect the source and build an extraction recipe automatically."/><Card className="cal-form-card"><form onSubmit={submit} className="cal-form-stack">{error && <ErrorState message={error}/>}<Field label="Source name"><input className="cal-input" name="name" required placeholder="Downtown Arts Council"/></Field><fieldset className="cal-segment-field"><legend>Source type</legend><div><button type="button" aria-pressed={type === 'web'} onClick={() => setType('web')}><Globe2 size={18}/><strong>Website</strong><span>Crawl a public events page</span></button><button type="button" aria-pressed={type === 'email'} onClick={() => setType('email')}><Mail size={18}/><strong>Email inbox</strong><span>Process incoming announcements</span></button></div></fieldset>{type === 'web' && <Field label="Website URL" hint="Use the page that lists upcoming events, not a general homepage."><input className="cal-input" name="url" type="url" required placeholder="https://example.org/events"/></Field>}<Field label="Special instructions" hint="Optional guidance for unusual layouts, recurring events, or fields to ignore."><textarea className="cal-textarea" name="specialInstructions" rows={5} placeholder="Event dates appear inside each accordion panel..."/></Field>{me.role === 'platform_admin' && <Field label="Community"><select className="cal-select" name="communityId" defaultValue={communityId ?? ''} required><option value="" disabled>Select a community</option>{communities.map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select></Field>}<div className="cal-form-actions"><Link href="/sources"><Button type="button" variant="secondary">Cancel</Button></Link><LoadingButton busy={busy}>Add and discover<ArrowRight size={16}/></LoadingButton></div></form><aside className="cal-form-aside"><div className="cal-aside-icon"><Radar size={22}/></div><h3>What happens next</h3><ol><li><span>1</span><p><strong>Source discovery</strong> maps the page or inbox structure.</p></li><li><span>2</span><p><strong>Recipe creation</strong> captures the extraction method and instructions.</p></li><li><span>3</span><p><strong>First run</strong> finds events for review or automatic publishing.</p></li></ol></aside></Card></>;
}

export function SourceDetailPage({ id }: { id: number }) {
  const router = useRouter();
  const query = useApi<{ source: Source; recentRuns: Run[] }>(`/api/sources/${id}`);
  const [busy, setBusy] = useState('');
  async function trigger(kind: 'run' | 'discover') { setBusy(kind); try { const result = await api<{ runId: number }>(`/api/sources/${id}/${kind}`, { method: 'POST' }); router.push(`/runs/${result.runId}`); } finally { setBusy(''); } }
  async function changeMode(mode: string) { await api(`/api/sources/${id}`, { method: 'PATCH', body: JSON.stringify({ mode }) }); await query.reload(); }
  if (query.loading) return <Skeleton rows={8}/>; if (query.error || !query.data) return <ErrorState message={query.error || 'Source not found'} retry={query.reload}/>;
  const { source, recentRuns } = query.data;
  return <><PageHeader eyebrow="Source detail" title={source.name} description={source.url || `${source.sourceType} ingestion source`} actions={<><LoadingButton busy={busy === 'discover'} variant="secondary" onClick={() => trigger('discover')}><RefreshCw size={15}/>Re-discover</LoadingButton><LoadingButton busy={busy === 'run'} onClick={() => trigger('run')}><Play size={15}/>Run now</LoadingButton></>}/><div className="cal-detail-grid"><div className="cal-stack"><Card><div className="cal-card-header"><div><h2>Configuration</h2><p>How this source extracts and routes events.</p></div><StatusBadge status={source.discoveryStatus}/></div><dl className="cal-detail-list"><div><dt>Source type</dt><dd>{source.sourceType}</dd></div><div><dt>Organization</dt><dd>{source.orgName || 'Not detected'}</dd></div><div><dt>Schedule</dt><dd>{source.scheduleCron || 'Manual only'}</dd></div><div><dt>Extraction method</dt><dd>{source.extractionRecipe?.extraction_method || 'Pending discovery'}</dd></div><div><dt>Destination</dt><dd>{source.destinationId ? `Destination ${source.destinationId}` : 'Community default'}</dd></div></dl><div className="cal-mode-control"><div><strong>Publishing mode</strong><span>Restricted mode sends every event to review.</span></div><select className="cal-select" value={source.mode || ''} onChange={event => changeMode(event.target.value)}><option value="">Community default</option><option value="restricted">Restricted</option><option value="unrestricted">Unrestricted</option></select></div></Card><Card><div className="cal-card-header"><div><h2>Special instructions</h2><p>Source-specific guidance supplied to the extraction agent.</p></div><Settings2 size={18}/></div><p className="cal-prose">{source.specialInstructions || 'No special instructions have been added.'}</p>{source.extractionRecipe && <details className="cal-recipe"><summary>View extraction recipe</summary><pre>{JSON.stringify(source.extractionRecipe, null, 2)}</pre></details>}</Card></div><Card><div className="cal-card-header"><div><h2>Recent runs</h2><p>Discovery and extraction history.</p></div><Badge>{recentRuns.length}</Badge></div>{recentRuns.length ? <div className="cal-list">{recentRuns.map(run => <Link href={`/runs/${run.id}`} className="cal-run-row cal-run-row--compact" key={run.id}><div className="cal-list-icon">{run.runKind === 'discovery' ? <Radar size={16}/> : <Activity size={16}/>}</div><div><strong>Run #{run.id}</strong><span>{formatDate(run.startedAt)}</span></div><StatusBadge status={run.status}/><ArrowRight size={15}/></Link>)}</div> : <EmptyState icon={<Clock3 size={20}/>} title="No runs yet" body="Run the source to begin collecting events."/>}</Card></div></>;
}
